"""SecAudit — Reports: HTML Report Generator"""
from datetime import datetime, timezone
from ..utils.logger import get_logger
logger = get_logger("reports.html")

async def generate_html_report(scan_data: dict) -> str:
    """Generate a styled HTML vulnerability report."""
    target = scan_data.get("target", "N/A")
    score = scan_data.get("score", 0)
    summary = scan_data.get("summary", {})
    vulns = scan_data.get("vulnerabilities", [])
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    severity_colors = {"Critical": "#dc2626", "High": "#ea580c", "Medium": "#ca8a04", "Low": "#2563eb", "Info": "#6b7280"}

    vuln_rows = ""
    for v in vulns:
        color = severity_colors.get(v.get("severity", ""), "#6b7280")
        vuln_rows += f"""<tr>
            <td><span style="background:{color};color:white;padding:2px 8px;border-radius:4px;font-size:12px;">{v.get('severity','')}</span></td>
            <td><strong>{v.get('name','')}</strong></td>
            <td>{v.get('file', v.get('url', 'N/A'))}</td>
            <td>{v.get('description','')[:200]}</td>
            <td><em>{v.get('remediation','')[:150]}</em></td>
        </tr>"""

    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>SecAudit Report — {target}</title>
<style>
body {{ font-family: 'Segoe UI', system-ui, sans-serif; margin: 0; padding: 40px; background: #0f0f23; color: #e2e8f0; }}
.container {{ max-width: 1000px; margin: 0 auto; }}
h1 {{ color: #818cf8; }} h2 {{ color: #a78bfa; border-bottom: 1px solid #334155; padding-bottom: 8px; }}
.stats {{ display: grid; grid-template-columns: repeat(5, 1fr); gap: 12px; margin: 20px 0; }}
.stat {{ background: #1e1e3f; padding: 16px; border-radius: 8px; text-align: center; }}
.stat .num {{ font-size: 28px; font-weight: bold; }}
table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
th {{ background: #1e1e3f; padding: 12px; text-align: left; }} td {{ padding: 10px; border-bottom: 1px solid #1e293b; }}
.score {{ font-size: 48px; font-weight: bold; color: {'#22c55e' if score >= 80 else '#ca8a04' if score >= 50 else '#dc2626'}; }}
</style></head><body><div class="container">
<h1>🛡️ SecAudit Security Report</h1>
<p>Target: <strong>{target}</strong> | Generated: {now}</p>
<div class="score">{score}/100</div>
<div class="stats">
    <div class="stat"><div class="num">{summary.get('total', len(vulns))}</div>Total</div>
    <div class="stat"><div class="num" style="color:#dc2626">{summary.get('critical',0)}</div>Critical</div>
    <div class="stat"><div class="num" style="color:#ea580c">{summary.get('high',0)}</div>High</div>
    <div class="stat"><div class="num" style="color:#ca8a04">{summary.get('medium',0)}</div>Medium</div>
    <div class="stat"><div class="num" style="color:#2563eb">{summary.get('low',0)}</div>Low</div>
</div>
<h2>Detected Vulnerabilities</h2>
<table><tr><th>Severity</th><th>Issue</th><th>Location</th><th>Description</th><th>Remediation</th></tr>
{vuln_rows}</table>
<p style="color:#64748b;margin-top:40px;">Generated by SecAudit AI Vulnerability Scanner v2.0</p>
</div></body></html>"""
